---
- name: Provision Image
  hosts: default
  tasks:
    - name: Install Yay AUR helper
      include_role:
        name: yay
    - name: Install oVirt Guest Additions
      include_role:
        name: ovirt_guest
