---
- name: Install Yay dependencies.
  become: yes
  package:
    name: "{{ yay_dependency_package_names }}"
    state: present
- name: Clone Yay PKDBUILD.
  git:
    repo: "{{ yay_git_repository_url }}"
    dest: "{{ yay_build_dir }}"
    clone: yes
- name: Build and install Yay.
  command: >
    makepkg --syncdeps --install --noconfirm --rmdeps
  args:
    chdir: "{{ yay_build_dir }}"

