---
- name: Install Yay dependencies.
  package:
    name: "{{ yay_dependency_package_names }}"
    state: present
- name: Clone Yay PKDBUILD.
  become_user: "{{ ansible_user_id }}"
  git:
    repo: "{{ yay_git_repository_url }}"
    dest: "{{ yay_build_dir }}"
    clone: yes
- name: Build and install Yay.
  become_user: "{{ ansible_user_id }}"
  command: >
    makepkg -si
  args:
    chdir: "{{ yay_build_dir }}"

